---
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-agent-k8s-conf
  labels:
    app: opentelemetry
    component: otel-agent-k8s-conf
data:
  otel-agent-k8s-config: |
    receivers:
      k8s_cluster: {}
      kubeletstats:
        auth_type: "serviceAccount"
        endpoint: "${KUBERNETES_PORT_443_TCP_ADDR}/api/v1/nodes/${K8S_NODE_NAME}/proxy"
        insecure_skip_verify: true
    exporters:
      otlp:
        endpoint: "otel-gateway.otel.svc.cluster.local:4317"
        insecure: true
        sending_queue:
          num_consumers: 4
          queue_size: 100
        retry_on_failure:
          enabled: true
    processors:
      batch:
      memory_limiter:
        # Same as --mem-ballast-size-mib CLI argument
        ballast_size_mib: 165
        # 80% of maximum memory up to 2G
        limit_mib: 400
        # 25% of limit up to 2G
        spike_limit_mib: 100
        check_interval: 5s
        #k8s.cluster.name
    extensions:
      health_check: {}
      zpages: {}
    service:
      extensions: [health_check, zpages]
      pipelines:
        metrics/k8s:
          receivers: [k8s_cluster, kubeletstats]
          processors: [memory_limiter, batch]
          exporters: [otlp]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-agent-k8s
  labels:
    app: opentelemetry
    component: otel-agent-k8s
spec:
  selector:
    matchLabels:
      app: opentelemetry
      component: otel-agent-k8s
  template:
    metadata:
      labels:
        app: opentelemetry
        component: otel-agent-k8s
    spec:
      serviceAccountName: otel-agent-k8s-sa
      containers:
      - args:
          - "--config=/conf/otel-agent-k8s-config.yaml"
          # Memory Ballast size should be max 1/3 to 1/2 of memory.
          - "--mem-ballast-size-mib=165"
        image: otel/opentelemetry-collector-contrib-dev:latest
        name: otel-agent-k8s
        env:
        - name: K8S_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName        
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 55679 # ZPages endpoint.
        - containerPort: 4317 # Default OpenTelemetry receiver port.
        - containerPort: 8888  # Metrics.
        volumeMounts:
        - name: otel-agent-k8s-config-vol
          mountPath: /conf
        livenessProbe:
          httpGet:
            path: /
            port: 13133 # Health Check extension default port.
        readinessProbe:
          httpGet:
            path: /
            port: 13133 # Health Check extension default port.
      volumes:
        - configMap:
            name: otel-agent-k8s-conf
            items:
              - key: otel-agent-k8s-config
                path: otel-agent-k8s-config.yaml
          name: otel-agent-k8s-config-vol
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: otel-agent-k8s-sa
  labels:
    app: otel-agent-k8s
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: otel-agent-k8s-role
rules:
  - apiGroups:
    - ""
    resources:
    - events
    - namespaces
    - namespaces/status
    - nodes
    - nodes/spec
    - nodes/proxy
    - pods
    - pods/status
    - replicationcontrollers
    - replicationcontrollers/status
    - resourcequotas
    - services
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - apps
    resources:
    - daemonsets
    - deployments
    - replicasets
    - statefulsets
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - extensions
    resources:
    - daemonsets
    - deployments
    - replicasets
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - batch
    resources:
    - jobs
    - cronjobs
    verbs:
    - get
    - list
    - watch
  - apiGroups:
      - autoscaling
    resources:
      - horizontalpodautoscalers
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-otel-agent-k8s-role
subjects:
  - kind: ServiceAccount
    name: otel-agent-k8s-sa
    namespace: otel
roleRef:
  kind: ClusterRole
  name: otel-agent-k8s-role
  apiGroup: rbac.authorization.k8s.io
